openapi: 3.0.3
info:
  title: KIV/PIA REST API
  description: blah
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: Local development server
tags:
  - name: "Auth"
    description: API endpoints used for authentication and user registration.
  - name: Projects
    description: API endpoints used for management of translation projects.
  - name: Users
    description: API endpoints used for management of users (customers, translators, admins).
paths:

  # ----- Auth Endpoints -----
  /auth/login:
    post:
      tags:
        - "Auth"
      summary: Authenticates a user and returns a JWT token.
      description: >
        Takes user credentials (email and password) and returns
        a JWT access token if the credentials are valid.
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'

      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthJWTResponse'
        '400':
          description: Request body is not formatted correctly.
        '401':
          description: Invalid email or password.
        '500':
          description: Server error.
  /auth/register:
    post:
      tags:
        - "Auth"
      summary: Register a user and returns a JWT token.
      operationId: registerUser
      description: >
        Registers a new user (customer or translator) and returns
        a JWT access token upon successful registration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '201':
          description: Registered successfully and created a new user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthJWTResponse'
        '400':
          description: Request body is not formatted correctly.
        '409':
          description: Email address is already in use.
        '500':
          description: Server error.
  /auth/refresh:
    post:
      tags:
        - Auth
      summary: Refreshes a JWT token
      description: >
        Takes a valid refresh token (usually from HttpOnly cookie)
        and issues a new access token. The refresh token itself
        is verified server-side.
      operationId: refreshToken
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: Token refreshed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthJWTResponse'
        '401':
          description: Invalid or expired refresh token.
        '500':
          description: Server error.
  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logs out the current user
      description: >
        Invalidates the current refresh token (server-side) and clears
        any authentication cookies. On the client side, the access token
        should also be deleted.
      operationId: logoutUser
      security:
        - bearerAuth: [ ]
        - cookieAuth: [ ]
      responses:
        '204':
          description: Logged out successfully (no content returned).
        '401':
          description: Unauthorized - no valid authentication token provided.
        '500':
          description: Server error.
  /me:
    get:
      tags:
        - Users
      summary: Get the currently authenticated user's details
      operationId: getCurrentUser
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Current user details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - no valid authentication token provided.
        '500':
          description: Server error.


    # ------ END Auth Endpoints ------





    # ----- Project Endpoints -----


  # ----- User Endpoints -----
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      operationId: listAllUsers
      description: >
        Retrieves a list of all users in the system. Using provided filters.
      parameters:
        - name: role
          in: query
          description: Filter users by their role (CUSTOMER, TRANSLATOR, ADMIN)
          required: false
          schema:
            $ref: '#/components/schemas/UserRole'
        - name: languages
          in: query
          description: Filter users by a language they know (ISO code, e.g., "en" for English)
          required: false
          schema:
            type: string
            example: en
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListUsersResponse'
        '401':
          description: Unauthorized - no valid authentication token provided.
        '403':
          description: Forbidden - insufficient permissions to access this resource.
        '500':
          description: Server error
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      operationId: getUserDetails
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - no valid authentication token provided.
        '403':
          description: Forbidden - insufficient permissions to access this resource.
        '404':
          description: User not found

  /users/{id}/languages:
    get:
      tags:
        - Users
      summary: Get languages known by a user
      operationId: listUserLanguages
      description: >
        Retrieves the list of languages known by the specified user.
        Accessible by ADMIN or the user themself (SELF).
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Languages retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLanguagesResponse'
        '401':
          description: Unauthorized - no valid authentication token provided.
        '403':
          description: Forbidden - insufficient permissions to access this resource.
        '404':
          description: User not found

    put:
      tags:
        - Users
      summary: Replace all languages of a user
      operationId: replaceUserLanguages
      description: >
        Replaces all existing languages of the specified user with a new set.
        Accessible by ADMIN or the user themself (SELF).
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReplaceLanguagesRequest'
      responses:
        '200':
          description: Languages replaced successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLanguagesResponse'
        '400':
          description: Invalid input data.
        '401':
          description: Unauthorized - no valid authentication token provided.
        '403':
          description: Forbidden - insufficient permissions to modify this resource.
        '404':
          description: User not found.
        '405':
          description: Unsupported HTTP method.
        '500':
          description: Internal server error.



  /projects:
    post:
      tags:
        - Projects
      summary: Creates a new project using the current user as the customer.
      operationId: createProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProjectRequest"
        required: true
      responses:
        '201':
          description: Project was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '400':
          description: Request body is not formatted correctly.
        '403':
          description: Current user is not authorized to create projects.
        '405':
          description: Unsupported HTTP method.
        '406':
          description: Not acceptable response representation.
        '500':
          description: Server error.
    get:
      tags:
        - Projects
      summary: List all projects with optional filters.
      operationId: listAllProjects
      parameters:
        - in: query
          name: state
          schema:
            $ref: '#/components/schemas/ProjectState'
          description: Filter projects by their state.
        - in: query
          name: languageCode
          schema:
            type: string
            minLength: 2
            maxLength: 2
            description: Filter projects by target language (ISO 639-1 code).
        - in: query
          name: hasFeedback
          schema:
            type: boolean
            description: Filter projects based on whether they have feedback.


      responses:
        '201':
          description: Project was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '400':
          description: Request body is not formatted correctly.
        '403':
          description: Current user is not authorized to create projects.
        '405':
          description: Unsupported HTTP method.
        '406':
          description: Not acceptable response representation.
        '500':
          description: Server error.





















components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken





  schemas:
    #----- User Schemas -----
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        name:
          type: string
          example: "John Doe"
        emailAddress:
          type: string
          format: email
          example: "john.doe@example.com"
        role:
          $ref: '#/components/schemas/UserRole'
        languages:
          type: array
          items:
            type: string
            example: "en"
          description: ISO language codes
        createdAt:
          type: string
          format: date-time
          example: "2025-10-15T09:33:20Z"
      required:
        - id
        - name
        - emailAddress
        - role
        - createdAt
    UserRole:
      type: string
      enum:
        - CUSTOMER
        - TRANSLATOR
        - ADMIN
    
    #??? MAYBE HEADERS ???
    UserHeader:
      type: object
      description: A lightweight user representation for headers
      properties:
        id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        name:
          type: string
          example: "John Doe"
        role:
          $ref: '#/components/schemas/UserRole'
      required:
        - id
        - name
        - role
    ### USER REQUESTS ###
    ReplaceLanguagesRequest:
      type: array
      items:
        type: string
        example: en
    ### USER RESPONSES ###
    ListUsersResponse:
      type: array
      items:
        $ref: '#/components/schemas/User'
    ListLanguagesResponse:
      type: array
      items:
        type: string
        example: en





    #----- Auth Schemas -----
    LoginUserRequest:
      type: object
      required: [ emailAddress, password ]
      additionalProperties: false
      properties:
        emailAddress:
          type: string
          format: email
        password:
          type: string
          format: password
    RegisterUserRequest:
      oneOf:
        - $ref: '#/components/schemas/RegisterCustomerRequest'
        - $ref: '#/components/schemas/RegisterTranslatorRequest'
      discriminator:
        propertyName: type
        mapping:
          customer: '#/components/schemas/RegisterCustomerRequest'
          translator: '#/components/schemas/RegisterTranslatorRequest'
    RegisterCustomerRequest:
      type: object
      required: [ name, emailAddress, password ]
      additionalProperties: false
      properties:
        type:
          type: string
          example: customer
        name:
          type: string
        emailAddress:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
    RegisterTranslatorRequest:
      type: object
      required: [ name, emailAddress, password, languages ]
      additionalProperties: false
      properties:
        type:
          type: string
          example: translator
        name:
          type: string
        emailAddress:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
        languages:
          type: array
          items:
            type: string
    ### AUTH RESPONSES ###
    AuthJWTResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      required:
        - accessToken



    #----- Project Schemas -----
    Project:
      type: object
      properties:
        projectId:
          type: string
          format: uuid
          description: Unique identifier of the created project
        languageCode:
          type: string
          example: "de"
        customer:
          $ref:
            '#/components/schemas/User'
        translator:
          $ref:
            '#/components/schemas/User'
        state:
          $ref: '#/components/schemas/ProjectState'
        createdAt:
          type: string
          format: date-time



    ProjectState:
      type: string
      enum:
        - CREATED
        - ASSIGNED
        - COMPLETED
        - APPROVED
        - CLOSED

    ### PROJECT REQUESTS ###
    CreateProjectRequest:
      type: object
      required: [ languageCode, content ]
      additionalProperties: false
      properties:
        customerId:
          type: string
          format: uuid
          description: >
            ID of the customer creating the project.  
            Optional — will use the authenticated user if omitted.
        languageCode:
          type: string
          minLength: 2
          maxLength: 2
          example: "de"
          description: Target language ISO 639-1 code.
        content:
          type: string
          format: binary
          description: Source file or text content to translate.

    ### PROJECT RESPONSES ###
    ListProjectsResponse:
      type: array
      items:
        $ref: '#/components/schemas/Project'

